[build]
buildCommand = "turbo run build --filter=@unseen-gadget/backend..."

[deploy]
startCommand = "npx --yes prisma db push --schema=packages/database/prisma/schema.prisma --accept-data-loss && node apps/backend/dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
