import { Router } from "express";
import authRoutes from "./auth.routes";
import adminAuthRoutes from "./admin-auth.routes";
import catalogRoutes from "./catalog.routes";
import productRoutes from "./product.routes";
import adminCatalogRoutes from "./admin-catalog.routes";
import cartRoutes from "./cart.routes";
import wishlistRoutes from "./wishlist.routes";
import addressRoutes from "./address.routes";
import orderRoutes from "./order.routes";
import paymentRoutes from "./payment.routes";
import dashboardRoutes from "./dashboard.routes";
import reportsRoutes from "./reports.routes";
import couponRoutes from "./coupon.routes";
import reviewRoutes from "./review.routes";
import contactRoutes from "./contact.routes";
import newsletterRoutes from "./newsletter.routes";
import articleRoutes from "./article.routes";
import jobRoutes from "./job.routes";
import cmsRoutes from "./cms.routes";
import adminOpsRoutes from "./admin-ops.routes";
import returnRoutes from "./return.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/admin/auth", adminAuthRoutes);
router.use("/catalog", catalogRoutes);
router.use("/products", productRoutes);
router.use("/admin", adminCatalogRoutes);
router.use("/admin", adminOpsRoutes);
router.use("/cart", cartRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/address", addressRoutes);
router.use("/addresses", addressRoutes);
router.use("/order", orderRoutes);
router.use("/orders", orderRoutes);
router.use("/payment", paymentRoutes);
router.use("/payments", paymentRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportsRoutes);
router.use("/coupon", couponRoutes);
router.use("/coupons", couponRoutes);
router.use("/review", reviewRoutes);
router.use("/reviews", reviewRoutes);
router.use("/return", returnRoutes);
router.use("/returns", returnRoutes);
router.use("/contact", contactRoutes);
router.use("/newsletter", newsletterRoutes);
router.use("/article", articleRoutes);
router.use("/articles", articleRoutes);
router.use("/job", jobRoutes);
router.use("/jobs", jobRoutes);
router.use("/cms", cmsRoutes);

export const apiRouter = router;
export default router;